version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: travel_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel_db
    ports:
      - "5432:5432"
    volumes:
      - travel_db_data:/var/lib/postgresql/data

volumes:
  travel_db_data:
